global:
  project: helmless
  region: europe-west1

env: &env 
  COLOR: "blue"

service:
  name: my-service
  image:
    name: "hello"
    repository: "us-docker.pkg.dev/cloudrun/container"
    tag: "latest"
  env:
    <<: *env 
    SERVICE_VAR: "Helmless is awesome!"

job:
  name: my-job
  image:
    name: "hello-job"
    repository: "us-docker.pkg.dev/cloudrun/container"
    tag: "latest"
  env:
    <<: *env
    COLOR: "red"
    JOB_VAR: "Look ma, riding without a helm!"